approve_by_comment: true
approve_regex: '^(Approved|:shipit:|:\+1:|LGTM)'
reject_regex: '^(Rejected|:-1:)'
reset_on_push: false
reviewers:
  members:
  - ChadSki
  - Drflash55
  - ErmiyaEskandary
  - Evanito
  - FliiFe
  - K00sKlust
  name: default
  required: 3
